### ISSUE TITLE
Sass version of non-Bootstrap CSS

### ISSUE THREAD

**Issue by marnen** [mistic100/jQuery-QueryBuilder#269]
Hi there! I thought you might appreciate a Sass version of the non-Bootstrap CSS at http://querybuilder.js.org/dev/no-bootstrap.html. If you want me to make this into a pull request and add it to the repo, I can do that too.

```scss
.query-builder, .query-builder * {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

.query-builder {
  font-family: sans-serif;

  .pull-right {
    float: right !important;
  }

  .btn {
    @mixin action-button($base-color, $border-color, $active-color) {
      color: #FFF;
      background-color: $base-color;
      border-color: $border-color;

      &.active, &.focus,
      &:active, &:focus,
      &:hover {
        color: #FFF;
        background-color: $active-color;
        border-color: darken($active-color, 7);
      }
    }

    text-transform: none;
    display: inline-block;
    padding: 6px 12px;
    margin-bottom: 0px;
    font-size: 14px;
    font-weight: 400;
    line-height: 1.42857;
    text-align: center;
    white-space: nowrap;
    vertical-align: middle;
    touch-action: manipulation;
    cursor: pointer;
    user-select: none;
    background-image: none;
    border: 1px solid transparent;
    border-radius: 4px;

    &.focus, &:focus, &:hover {
      color: #333;
      text-decoration: none;
    }

    &.active, &:active {
      background-image: none;
      outline: 0px none;
      box-shadow: 0px 3px 5px rgba(0, 0, 0, 0.125) inset;
    }

    &-success {
      $base-color: #5cb85c;
      @include action-button(
        $base-color: $base-color,
        $border-color: darken($base-color, 5),
        $active-color: #449d44
      );
    }

    &-primary {
      $base-color: #337AB7;
      @include action-button(
        $base-color: $base-color,
        $border-color: darken($base-color, 4),
        $active-color: darken($base-color, 9)
      );
    }

    &-danger {
      @include action-button($base-color: #D9534F, $border-color: #D43F3A, $active-color: #c9302c);
    }
  }

  .btn-group {
    position: relative;
    display: inline-block;
    vertical-align: middle;

    & > .btn {
      position: relative;
      float: left;

      &:first-child {
        margin-left: 0px;

        &:not(:last-child) {
          border-top-right-radius: 0px;
          border-bottom-right-radius: 0px;
        }
      }

      &:last-child:not(:first-child) {
        border-top-left-radius: 0px;
        border-bottom-left-radius: 0px;
      }
    }

    .btn + .btn, .btn + .btn-group,
    .btn-group + .btn, .btn-group + .btn-group {
      margin-left: -1px;
    }
  }

  .btn-xs, .btn-group-xs > .btn {
    padding: 1px 5px;
    font-size: 12px;
    line-height: 1.5;
    border-radius: 3px;
  }
}
```
