### ISSUE TITLE
View actions only on mouse over!

### ISSUE THREAD

**Issue by aadrian** [mistic100/jQuery-QueryBuilder#373]
Please add support to be able to configure the visibility of the actions: invert,  (non-active and/or), add group, add rule, delete, drag, info **only** when the mouse is over (entered) the filter panel.

This would highly increase the readability of a filter when present in a page, and when the user whats to edit something, they'll e displayed anyways.

Thank you.

**Comment by mistic100** [comment]
You can do it yourself

```css
.rule-container .rule-actions {
  display: none;
}

.rule-container:hover .rule-actions {
  display: block;
}
```
