### ISSUE TITLE
Provide only one operator make a strange display

### ISSUE THREAD

**Issue by Rapster** [mistic100/jQuery-QueryBuilder#412]
Based on this demo: https://jsfiddle.net/Rapster/89byg4wh/
Reproducing the problem is quite easy, just select "Select CMIS Type" and then you'll see this:

![image](https://cloud.githubusercontent.com/assets/7521311/21549403/42e2e934-cdf2-11e6-9596-0ca82e1dee8b.png)

In my opinion, only text "equal" should be displayed but not the select input.

**Comment by mistic100** [comment]
The "no bootstrap" stylesheet is missing the following :
```css
.query-builder .hide {
  display: none;
}
```

**Comment by Rapster** [comment]
Thanks ;)

**Comment by Rapster** [comment]
By the way, is this style really necessary?
```css
.query-builder {
  font-family: sans-serif;
}
```
